####
# Native micro image (smallest footprint)
#
# ./mvnw package -Dnative
# docker build -f src/main/docker/Dockerfile.native-micro -t egripp/quarkus-native-template/template-service-micro:1.0.0 .
####
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 9090
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=9090"]
